version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.1
  nx: nrwl/nx@1.6.2
jobs:
  build:
    docker:
      - image: cimg/node:24.18-browsers
    resource_class: large
    environment:
      LOGS_DIR: /tmp/ngx-mime-build/logs
      BROWSER_PROVIDER_READY_FILE: /tmp/ngx-mime-build/readyfile
    steps:
      - checkout
      - browser-tools/install-chrome
      - run:
          command: yarn install --immutable
          name: Install dependencies
      - nx/set-shas
      - run: 'mkdir -p $LOGS_DIR'
      - run:
          name: Check formatting
          command: npx nx format:check
      - run:
          name: Lint, test, and build affected projects
          command: npx nx affected --base="$NX_BASE" --head="$NX_HEAD" -t lint,test,build --parallel=2
      - run:
          name: Run end-to-end tests
          no_output_timeout: 60m
          command: npx nx e2e integration-e2e
