version: 2.1
orbs:
  browser-tools: circleci/browser-tools@2.4.2
  nx: nrwl/nx@1.7.0
jobs:
  build:
    docker:
      - image: cimg/node:24.18-browsers
    resource_class: large
    steps:
      - checkout
      - browser-tools/install_chrome
      - run:
          command: yarn install --immutable
          name: Install dependencies
      - nx/set-shas:
          main-branch-name: main
      - run:
          name: Check formatting
          command: npx nx format:check
      - run:
          name: Lint, test, and build affected projects
          command: npx nx affected --base="$NX_BASE" --head="$NX_HEAD" -t lint,test,build --parallel=2
      - run:
          name: Run end-to-end tests
          no_output_timeout: 60m
          command: npx nx e2e integration-e2e
