name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v7
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: yarn

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - uses: nrwl/nx-set-shas@v5

      - name: Check formatting
        run: npx nx format:check

      - name: Lint, test, and build affected projects
        run: npx nx affected -t lint test build --parallel=2

      - name: Install Chrome
        run: npx playwright install --with-deps chrome

      - name: Run end-to-end tests
        if: github.event_name == 'pull_request'
        run: npx nx e2e integration-e2e

      - name: Run remote end-to-end tests
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: npx nx e2e integration-e2e -c remote
